/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 flutter.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/flutter.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.node_id3.geometry} material={materials['60']} position={[0.199, -0.041, 0.35]} rotation={[-0.016, 1.376, 0]} scale={0.014} />
    </group>
  )
}

useGLTF.preload('/flutter.glb')
